Add first and last page buttons to transaction page
franky47/centralized-coin-explorer pull request #5
Opened 2021-04-27 12:20 UTC by mustardpower

Can now navigate to first and last page via two additional buttons. Need some limitation to prevent navigation past the last page?

2021-04-27 13:43 UTC, franky47 requested changes

2021-04-27 13:43 UTC, franky47 commented on src/client/components/PageNavigation.tsx
> +import { getNumberOfPages } from 'src/services/centralized-coin'
Could you merge the imports please ?

2021-04-27 13:43 UTC, franky47 commented on src/client/components/PageNavigation.tsx
> +    (value: number) => { setPage(page => value)
This line breaks when building, probably just `setPage(value)` ?

2021-04-27 13:43 UTC, franky47 commented on src/client/components/PageNavigation.tsx
> +  const first = React.useCallback(() => setPage(page => 0), [])
Same here as above.

2021-04-27 16:19 UTC, franky47 approved these changes
LGTM!

2021-04-27 16:34 UTC, mustardpower commented
There is actually an error with the number of pages calculation - doesn't currently account for any remaining transactions on the last page that isn't completely full.

2021-04-27 17:01 UTC, mustardpower commented
I am unsure about the page number calculation. I checked there are 50 transactions on the page but the api endpoint is returning 2772 at this moment in time. However, in the transaction explorer I see only 2 transactions on the last page. Should be 22?

2021-04-27 18:45 UTC, franky47 requested changes

2021-04-27 18:45 UTC, franky47 commented on src/services/centralized-coin.ts
> +  return Math.floor(numberOfTransactions/ transactionsPerPage);
This should probably be `Math.ceil`, to account for the last page.

Eg, if there were 55 transactions, 55/50 = 1.1, there would be 2 pages.

2021-04-28 06:10 UTC, franky47 approved these changes
LGTM! Do you want the coins on your Git committer email ? Otherwise, send me your address at contact@francoisbest.com

2021-04-28 06:10 UTC, merged